<?php

use Nette\Application\Routers\Route;
// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../libs/autoload.php';


$configurator = new Nette\Config\Configurator;

$configurator->enableDebugger(__DIR__ . '/../log');

$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
        ->addDirectory(__DIR__)
        ->addDirectory(__DIR__ . '/../libs')
        ->register();
$configurator->addConfig(__DIR__ . '/config/config.neon');
$container = $configurator->createContainer();
$router = $container->router;
$router[] = new Route('index.php', array(
            'presenter' => 'Event',
            'action' => 'default',
                ), Route::ONE_WAY);

$router[] = new Route('<presenter>/<action>[/<id>]', array(
            'presenter' => 'Event',
            'action' => 'default',
            'id' => NULL,
        ));
return $container;
